title: Maxwell Made
tagline: 
description: Custom woodworking projects made here
url: https://maxwellmade.ca
permalink: /:title
locale: en_CA
logo: /assets/images/logo.png

author:
  name: Michael Maxwell
  email: mmaxwellmade@gmail.com

collections:
  products:
    output: true
    permalink: /:name
    order:
      - chess-board.md
      - charcuterie.md
      - vinyl-shelf.md
      - bedframe.md
      - chess-pieces.md
      - cornhole.md
      - desktop.md
      - lead.md
      - ring-calendar.md
      - calendar-ring.md

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
  - scope:
      path: ""
    values:
      layout: "base"

exclude:
  - CNAME
  - README.md
